version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  docker_build_and_push:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USERNAME/myapp:${CIRCLE_SHA1} .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $DOCKER_USERNAME/myapp:${CIRCLE_SHA1}

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - docker_build_and_push:
          requires:
            - build_and_test
